{% set name = "bw2calc" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b13df4125b9716d8338fae7122f3771d42237220a80bd8e4e1d6319443dc9666

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - bw_processing >=1.0
    - eight
    - fsspec
    - matrix_utils >=0.5
    - numpy <2
    - pandas
    - pydantic
    - pypardiso  # [not (osx and arm64)]
    - python
    - scikit-umfpack  # [osx and arm64]
    - scipy
    - stats_arrays

test:
  imports:
    - bw2calc

about:
  home: https://github.com/brightway-lca/brightway2-calc
  summary: 'The calculation engine for the Brightway2 life cycle assessment framework.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-calc

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
