{% set name = "bw2calc" %}
{% set version = "2.0.dev18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c70f10cf8558e80fb66ddc56fc678b180d7274e26fab5b657c84e48b52cd1633

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - bw_processing >=0.9.5
    - fsspec
    - matrix_utils >=0.4.3
    - numpy <2  # [not (osx and arm64)]
    - numpy <=1.24  # [osx and arm64]
    - pandas
    - pydantic
    - scipy
    - stats_arrays
    - pypardiso  # [not (osx and arm64)]
    - scikit-umfpack  # [osx and arm64]

test:
  imports:
    - bw2calc

about:
  home: https://github.com/brightway-lca/brightway2-calc
  summary: 'The calculation engine for the Brightway life cycle assessment framework.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-calc

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
