{% set name = "bw2calc" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db7fe61b34989e52c143e176704d074b73eefda28cf92fb750862acbaefe70b8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=68.0
  run:
    - bw_processing >=1.0
    - fsspec
    - matrix_utils >=0.6
    - numpy <3
    - pandas
    - pydantic
    - pypardiso  # [not (osx and arm64)]
    - python
    - scikit-umfpack  # [osx and arm64]
    - scipy
    - stats_arrays

test:
  imports:
    - bw2calc

about:
  home: https://github.com/brightway-lca/brightway2-calc
  summary: 'The calculation engine for the Brightway2 life cycle assessment framework.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-calc

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
